# action.yml
name: 'Docker Language Tool'
description: 'Runs grammar and spellcheck on a string'
inputs:
  language: # what language to parse in
    description: 'What language to parse in'
    required: false
    default: 'en-US'
  filepath:
    description: 'The filepath of the file to be parsed'
    required: true
outputs:
  warnings: # id of output
    description: 'The warnings that were outputted'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.language }}
    - ${{ inputs.filepath }}
